#!/bin/bash

jupyter labextension install @jupyter-widgets/jupyterlab-manager 

cookiecutter --default-config https://github.com/jupyterlab/theme-cookiecutter
cd mytheme
jupyter labextension install . --debug

jupyter lab build
