#!/bin/bash

jupyter labextension install @jupyter-widgets/jupyterlab-manager 

cookiecutter --no-input https://github.com/jupyterlab/theme-cookiecutter
cd mytheme
echo 'h1 { color: #f00; text-transform: uppercase; font-weight: bold !important; }' >> mytheme/style/index.css
jupyter labextension install . --debug

jupyter lab build
